version: '3.7'

services:
    nginx:
        image: 'nginx-ja3'
        build: .
        ports:
          - '443:443'
        volumes:
          - ./nginx/nginx.conf:/usr/local/nginx/conf/nginx.conf
    openresty:
        image: openresty/openresty
        volumes:
          - ./openresty/lua:/lua
          - ./openresty/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
        ports:
          - 8080:80
    redis:
        image: redis
        ports:
          - 6379:6379
    redis-commander:
        container_name: redis-commander
        hostname: redis-commander
        image: rediscommander/redis-commander:latest
        restart: always
        environment:
            - REDIS_HOSTS=local:redis:6379
        ports:
            - "8888:8081"